In [1]:
person = ("Sunday","Data Science","Fall Session")

In [2]:
person1 = "Victoria","Data Science","Fall Session"

In [3]:
import pandas as pd

In [3]:
x = 50
y = 10
print('{0} * {1} = {2}'.format(x, y, x * y))

50 * 10 = 500


In [4]:
name = 'Mardiyah'
print('Hello %s' %name)

Hello Mardiyah


In [7]:
age = 20
print('Hello %s! are you %d years old?' %(name, age))

Hello Mardiyah! are you 20 years old?


In [8]:
value = input('Enter some value:')

Enter some value:25


In [9]:
value

'25'

In [12]:
value = int(input('Enter some value: '))

Enter some value: 25


In [13]:
value

25

In [17]:
import math

10.0

In [21]:
True

True

In [22]:
x = 100

In [24]:
if x == 100:
    print('x is =', x)

x is = 100


In [25]:
name = input('Enter a name: ')
if name == 'Max':
    print('Name entered is : ', name)
elif name == 'Leo':
    print('Name entered is : ', name)
elif name == "Sun":
    print('Name entered is : ', name)
elif name == "Tin":
    print('Name entered is : ', name)
else:
    print("The name entered is invalid")

Enter a name: Leo
Name entered is :  Leo


In [33]:
email = input("Enter your email address: ")
name = ("Mardiyah","dara")
if email == "mardiyah@gmail.com":
    print("Welcome on board ", name[0])
elif email == "dara@gmail.com":
    print("Welcome on board", name[1])
else:
    print("your email does not exist")

Enter your email address: mardiyah@gmail.com
Welcome on board  Mardiyah


In [46]:
gender = "male"
age = int(input("Enter your age: "))
if gender == "male":
    print("you are eligble")
    if age < 10 or age > 13:
        print("you are not eligible")
else:
    print("try again later")

Enter your age: 11
you are eligble


In [47]:
x = [1,2,3,4,5,6]
s = x.copy()

In [48]:
s

[1, 2, 3, 4, 5, 6]

In [49]:
t = x + s
t

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [53]:
hello = ("hi",) * 5
print(hello)

('hi', 'hi', 'hi', 'hi', 'hi')


In [54]:
a = {1,2,3,2,5,3,7,6}

In [55]:
len(a)

6

In [56]:
a

{1, 2, 3, 5, 6, 7}

In [58]:
 x =set(x)

In [59]:
x

{1, 2, 3, 4, 5, 6}

In [60]:
a | x

{1, 2, 3, 4, 5, 6, 7}

In [61]:
a.union(x)

{1, 2, 3, 4, 5, 6, 7}

In [62]:
a.intersection(x)

{1, 2, 3, 5, 6}

In [63]:
a - x

{7}

In [1]:
 x = "I am"

In [2]:
y = "a girl"

In [3]:
print(x,y)

I am a girl


In [7]:
names = ["Mardiyah","Haymin","Zee","Ruby","Don"]
for name in names:
    print(f"{name}, Thank you for coming through")
print("Thank you all")

Mardiyah, Thank you for coming through
Haymin, Thank you for coming through
Zee, Thank you for coming through
Ruby, Thank you for coming through
Don, Thank you for coming through
Thank you all


In [8]:
names = ["Mardiyah","Haymin","Zee","Ruby","Don"]
for name in names:
    print(f"{name}, Thank you for coming through")
    print("Thank you all")

Mardiyah, Thank you for coming through
Thank you all
Haymin, Thank you for coming through
Thank you all
Zee, Thank you for coming through
Thank you all
Ruby, Thank you for coming through
Thank you all
Don, Thank you for coming through
Thank you all


In [9]:
#The Range Function

In [11]:
range(0,10)

range(0, 10)

In [12]:
lst = list(range(0,10))

In [13]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
#creating a list with list comprehension
for n in range(1,10):
    squares = n**2
    print(squares)

1
4
9
16
25
36
49
64
81


In [20]:
#list comprehension
square = [n ** 2 for n in range(1,10)]
print(square)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [24]:
#for loop and slicing lists

In [25]:
for n in square[:4]:
    print(n ** 2)

1
16
81
256


In [26]:
#copy of a list
square_copy = square[:]

In [27]:
square_copy

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [28]:
square

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [37]:
x = list(range(1,10))

In [38]:
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [1]:
#if statements

In [1]:
age = 17
if age >= 18:
    print('you are qualified to vote')

In [4]:
#if else statement

In [5]:
age = 17
if age >= 18:
    print('you are qualified to vote')
else:
    print('not qualified to vote')

not qualified to vote


In [2]:
#dictionaries

In [4]:
D = {'name':'max','year':2004,'age':14}

In [5]:
D['name'] = 'tom'

In [6]:
D

{'name': 'tom', 'year': 2004, 'age': 14}

In [7]:
D.update({'name':'max'})

In [8]:
D

{'name': 'max', 'year': 2004, 'age': 14}

In [10]:
D.items()

dict_items([('name', 'max'), ('year', 2004), ('age', 14)])

In [11]:
#while loop

In [13]:
i = 0
while i < 5:
    print('the value of i is:', i)
    i += 1
print('finished while loop')

the value of i is: 0
the value of i is: 1
the value of i is: 2
the value of i is: 3
the value of i is: 4
finished while loop


In [1]:
#quick dictionary
student_info = {'firstname':'Akinpelumi','age':12,'class':'jss3'}

In [4]:
'firstname' in student_info

True

In [5]:
student_info.items()

dict_items([('firstname', 'Akinpelumi'), ('age', 12), ('class', 'jss3')])

In [6]:
student_info.keys()

dict_keys(['firstname', 'age', 'class'])

In [7]:
old_key = 'firstname'
new_key = 'alias'

student_info[new_key] = student_info.pop(old_key)

In [8]:
student_info

{'age': 12, 'class': 'jss3', 'alias': 'Akinpelumi'}

In [9]:
revenue = {'months':['jan', 'feb', 'mar',
                    'apr', 'may','jun', 'jul',
                    'aug', 'sept', 'oct',
                    'nov', 'dec'],
          'monthly_sales': [120, 135, 150, 145, 155, 160, 170, 180, 190, 200, 210, 220] }

In [10]:
import pandas as pd

In [13]:
revenue_df = pd.DataFrame(revenue)

In [14]:
revenue_df

months  monthly_sales
0     jan            120
1     feb            135
2     mar            150
3     apr            145
4     may            155
5     jun            160
6     jul            170
7     aug            180
8    sept            190
9     oct            200
10    nov            210
11    dec            220

In [70]:
#creating a dictionary representing a library catalogue
LC = {'To kill a mockingbird':'Harper Lee','Gone with the wind':'Margaret Mitchell','As I lay dying':'William Faulkner',
      'The grapes of wrath':'John Steinbeck','The sun also rises':'Ernest Hemingway','Absalom, absalom!':'William Faulkner',
      'The house of mirth':'Edith Wharton','A time to kill':'John Grisham','Sarah,plain and tell':'Patricia MacLachlan'}

#creating a for loop to iterate over the dictionary
for booktitles,authors in LC.items():
    print(f'\nbooktitle: {booktitles}')
    print(f'author: {authors}')



booktitle: To kill a mockingbird
author: Harper Lee

booktitle: Gone with the wind
author: Margaret Mitchell

booktitle: As I lay dying
author: William Faulkner

booktitle: The grapes of wrath
author: John Steinbeck

booktitle: The sun also rises
author: Ernest Hemingway

booktitle: Absalom, absalom!
author: William Faulkner

booktitle: The house of mirth
author: Edith Wharton

booktitle: A time to kill
author: John Grisham

booktitle: Sarah,plain and tell
author: Patricia MacLachlan


In [ ]:
#creating a for loop so that readers can access author by typing in the book titles
LC = {'To kill a mockingbird':'Harper Lee','Gone with the wind':'Margaret Mitchell','As I lay dying':'William Faulkner',
      'The grapes of wrath':'John Steinbeck','The sun also rises':'Ernest Hemingway','Absalom, absalom!':'William Faulkner',
      'The house of mirth':'Edith Wharton','A time to kill':'John Grisham','Sarah,plain and tell':'Patricia MacLachlan'}

Search = input('Enter book title: ')
for booktitles,authors in LC.items():
    if Search == booktitles:
        print(f'author is: {authors}')
        break
else:
        print("booktitle is not in LC")

In [2]:
LC = {'To kill a mockingbird':'Harper Lee','Gone with the wind':'Margaret Mitchell','As I lay dying':'William Faulkner',
      'The grapes of wrath':'John Steinbeck','The sun also rises':'Ernest Hemingway','Absalom, absalom!':'William Faulkner',
      'The house of mirth':'Edith Wharton','A time to kill':'John Grisham','Sarah,plain and tell':'Patricia MacLachlan'}

search = input('Enter book title: ')
if search in LC:
    author = LC[search]
    print(f'author is:  {author}')
else:
    print(f"booktitle is not in LC")

Enter book title: fish
booktitle is not in LC


In [4]:
# allow users to add new books to the catalog by providing the title and author.
new_book = input('Enter title of book: ')
new_author = input('Enter name of author: ')
LC2 = LC[new_book] = new_author
print(f'The name of new book added is: {new_book} by {new_author}')

Enter title of book: In the early hours
Enter name of author: Kurram Murad
The name of new book added is: In the early hours by Kurram Murad


In [5]:
print(LC)

{'To kill a mockingbird': 'Harper Lee', 'Gone with the wind': 'Margaret Mitchell', 'As I lay dying': 'William Faulkner', 'The grapes of wrath': 'John Steinbeck', 'The sun also rises': 'Ernest Hemingway', 'Absalom, absalom!': 'William Faulkner', 'The house of mirth': 'Edith Wharton', 'A time to kill': 'John Grisham', 'Sarah,plain and tell': 'Patricia MacLachlan', 'In the early hours': 'Kurram Murad'}


In [6]:
len(LC)

10

In [10]:
# Create a dictionary that represents a dataset of 10 students' and thier test scores (4 courses). 
# The keys should be dictionaries bearing student names,
# in the nested dictionary, let the keys represent a course and the value a score for that course.
student_testscore1 = {"Mardiyah":{"Maths":10,"Eng":10,"Econs":9,"Science":10},"Tolani":{"Maths":8,"Eng":10,"Econs":7,
                    "Science":9},"Aisha":{"Maths":10,"Eng":7,"Econs":8,"Science":8},"Islamiyyah":{"Maths":9,"Eng":9,"Econs":9,
                    "Science":9},"Zainab":{"Maths":9,"Eng":10,"Econs":7,"Science":8},"Olamide":{"Maths":7,"Eng":7,"Econs":10,
                    "Science":10},"Seun":{"Maths":9,"Eng":10,"Econs":9,"Science":10},"Adam":{"Maths":10,"Eng":8,"Econs":9,
                    "Science":7},"Penne":{"Maths":8,"Eng":9,"Econs":10,"Science":9},"Tunde":{"Maths":9,"Eng":9,"Econs":8,
                    "Science":8}}

In [11]:
# Allow the user to input a student's name and display their average test score.
Sname = input("Enter student name: ")
if Sname in student_testscore1:
    student = student_testscore1[Sname]
    total_score = sum(student.values())
    avgTS = (total_score/len(student))
    print(f"Average test score for {Sname}: {avgTS}")
else:
    print(f"Student '{Sname}' not found.")

Enter student name: Mardiyah
Average test score for Mardiyah: 9.75


In [12]:
STS = {"Mardiyah":{"Maths":10,"Eng":10,"Econs":9,"Science":10},"Tolani":{"Maths":8,"Eng":10,"Econs":7,
                    "Science":9},"Aisha":{"Maths":10,"Eng":7,"Econs":8,"Science":8},"Islamiyyah":{"Maths":9,"Eng":9,"Econs":9,
                    "Science":9},"Zainab":{"Maths":9,"Eng":10,"Econs":7,"Science":8},"Olamide":{"Maths":7,"Eng":7,"Econs":10,
                    "Science":10},"Seun":{"Maths":9,"Eng":10,"Econs":9,"Science":10},"Adam":{"Maths":10,"Eng":8,"Econs":9,
                    "Science":7},"Penne":{"Maths":8,"Eng":9,"Econs":10,"Science":9},"Tunde":{"Maths":9,"Eng":9,"Econs":8,
                    "Science":8}}

In [14]:
Sname = input("Enter student name: ")
for name,score in STS.items():
    if Sname == name:
        STS1 =STS[Sname]
        TS = sum(STS1.values())
        ATS = TS/len(STS1)
        print(f"Average test score for {Sname}: {ATS}")
        break
else:
    print(f"Student '{Sname}' not found.")

Enter student name: Ada
Student 'Ada' not found.


In [54]:
# Create a DataFrame from the student test scores dictionary using pandas. Display the DataFrame to the user.
import pandas as pd
STS_df = pd.DataFrame(STS)

In [55]:
STS_df

Mardiyah  Tolani  Aisha  Islamiyyah  Zainab  Olamide  Seun  Adam  \
Maths          10       8     10           9       9        7     9    10   
Eng            10      10      7           9      10        7    10     8   
Econs           9       7      8           9       7       10     9     9   
Science        10       9      8           9       8       10    10     7   

         Penne  Tunde  
Maths        8      9  
Eng          9      9  
Econs       10      8  
Science      9      8

In [25]:
#creating a dictionary for a store's inventory
Store_Inventory = {'Milk':(10, 5),'Sugar':(8, 4),'Soap':(12, 3),'Chips':(10, 3),'Chocolate':(7, 7),'tea':(9, 4),'Rice':(9, 2),
                  'Custard':(12, 6),'Drink':(8, 6),'Water':(5, 15)}

# Allow the user to input a product name, and display its price and availability.
productName = input('Enter name of product: ')
for product, j in Store_Inventory.items():
    if productName == product:
            Product = Store_Inventory[product]
            Price = Product[0]
            quantity = Product[1]
            print (f'The price of {product} is {Price} and we have {quantity} left')
            break
else:
    print("The product you want is not available")

Enter name of product: Soap
The price of Soap is 12 and we have 3 left


In [ ]:
# Extend the online store program to allow users to "purchase" products by specifying the product name and the quantity they 
# want to buy and Update the inventory accordingly and display the total cost of the purchase
Store_Inventory = {'Milk':(10, 5),'Sugar':(8, 4),'Soap':(12, 3),'Chips':(10, 3),'Chocolate':(7, 7),'tea':(9, 4),'Rice':(9, 2),
                  'Custard':(12, 6),'Drink':(8, 6),'Water':(5, 15)}
CumAmount = 0
Count = 0
for product, j in Store_Inventory.items():
    productName = input('Enter name of product: ')
    if productName == product:
        Product = Store_Inventory[product]
        Price = Product[0]
        quantity = Product[1]
        #input a product name, and display its price and availability
        print (f'The price of {product} is {Price} and we have {quantity} left')
        QtyBought = int(input('quantity bought? '))
        PriceB = Price
        Amount = QtyBought * PriceB
        #Count = quantity - QtyBought
        print (f'Amount of {product} bought = {Amount}')
        # Update the inventory accordingly and display the total cost of the purchase
        CumAmount += Amount
        print (f'Total amount for products bought = {CumAmount}')
    else:
        print("The product you want is not available")
    #CumAmount += Amount
    #print (f'Total amount for products bought = {CumAmount}')

Enter name of product: Milk
The price of Milk is 10 and we have 5 left
quantity bought? 3
Amount of Milk bought = 30
Total amount for products bought = 30
Enter name of product: Sugar
The price of Sugar is 8 and we have 4 left
quantity bought? 2
Amount of Sugar bought = 16
Total amount for products bought = 46


In [3]:
x = (1,2,3,4,5)
x[0:2]

(1, 2)

In [5]:
#create 2 sets

In [6]:
set_one = {23,45,67,97,45}
set_two = {23,78,90,67,109}

In [9]:
#Union of set
set_three = set_one.union(set_two)
print(set_three)

{97, 67, 45, 109, 78, 23, 90}


In [10]:
#intersection of set
set_four = set_one.intersection(set_two)
print(set_four)

{67, 23}


In [8]:
# Create an empty glossary dictionary
glossary_dict = {}

#  Allow users to add new words and their definitions to the glossary.
def update_dict(new_word, new_meaning):
    new_word = input("Enter new glossary word: ")
    new_meaning = input("Enter definition of the word: ")
    glossary_dict[new_word] = new_meaning
    print(f'{new_word} has been added to the glossary with the definition {new_meaning}')
update_dict("word","definition")

Enter new glossary word: Laptop
Enter definition of the word: A small computer you can use on your lap
Laptop has been added to the glossary with the definition A small computer you can use on your lap


In [9]:
glossary_dict

{'Laptop': 'A small computer you can use on your lap'}

In [11]:
search = input("Type in the word you want to be defined: ")
for word, meaning in glossary_dict.items():
    if search == word:
        print(f'\nThe meaning of {search} is {meaning}')
    else:
        print("Word is not found")

Type in the word you want to be defined: book
Word is not found


In [3]:
#nested conditional
#nested if statement
age = int(input("Enter applicant's age: "))
vaccinated = input("Enter applicant's vaccination status (Y/N): ")
if age < 5:
    if vaccinated == "N":
        print("you are eligible")
    else:
        vaccinated == "Y"
        print("you have been vaccinated")
else:
    print("you are not eligible")

Enter applicant's age: 4
Enter applicant's vaccination status (Y/N): N
you are eligible


In [4]:
print("\U0001f914")

🤔


In [7]:
revenue = {'months':['jan', 'feb', 'mar', 'apr', 'may','jun', 'jul','aug', 'sept', 'oct','nov', 'dec'],
          'monthly_sales': [120, 135, 150, 145, 155, 160, 170, 180, 190, 200, 210, 220]}
# Introducing the zip function
for month, sales in zip(revenue['months'],revenue['monthly_sales']):
    print(month,sales)

jan 120
feb 135
mar 150
apr 145
may 155
jun 160
jul 170
aug 180
sept 190
oct 200
nov 210
dec 220


In [11]:
import pandas as pd
df = pd.DataFrame(revenue)

sales_categories = []
for index,rows in df.iterrows():
    sales = rows['monthly_sales']
    if sales < 150:
        category = 'Low'
    elif sales < 170:
        category = 'Medium'
    else:
        category = 'High'
    sales_categories.append(category)
    
df['sales category'] = sales_categories

In [12]:
df

months  monthly_sales sales category
0     jan            120            Low
1     feb            135            Low
2     mar            150         Medium
3     apr            145            Low
4     may            155         Medium
5     jun            160         Medium
6     jul            170           High
7     aug            180           High
8    sept            190           High
9     oct            200           High
10    nov            210           High
11    dec            220           High

In [1]:
#lambda function

In [4]:
a = lambda x,y : x ** (1/y)

In [5]:
a(2,5)

1.148698354997035

In [30]:
#creating a for loop so that readers can access author by typing in the book titles using functions
LibraryCat = {'To kill a mockingbird':'Harper Lee','Gone with the wind':'Margaret Mitchell','As I lay dying':'William Faulkner',
      'The grapes of wrath':'John Steinbeck','The sun also rises':'Ernest Hemingway','Absalom, absalom!':'William Faulkner',
      'The house of mirth':'Edith Wharton','A time to kill':'John Grisham','Sarah,plain and tell':'Patricia MacLachlan'}

def librarycat(Search):
    #Search = input('Enter book title: ')
    for booktitles,authors in LibraryCat.items():
        if Search == booktitles:
            print(f'author is: {authors}')
            break
    else:
        print("booktitle is not in LC")

In [31]:
librarycat("In the early hours")

booktitle is not in LC


In [33]:
# allow users to add new books to the catalog by providing the title and author using functions.
def updateCat(new_book):
    #new_book = input('Enter title of book: ')
    new_author = input('Enter name of author: ')
    LibraryCat[new_book] = new_author
    print(f'The name of new book added is: {new_book} by {new_author}')

In [37]:
updateCat("In the early hours")

Enter name of author: Khurram Murad
The name of new book added is: In the early hours by Khurram Murad


In [38]:
updateCat("Sweet sixteen")

Enter name of author: Bolaji Abdullahi
The name of new book added is: Sweet sixteen by Bolaji Abdullahi


In [39]:
LibraryCat

{'To kill a mockingbird': 'Harper Lee',
 'Gone with the wind': 'Margaret Mitchell',
 'As I lay dying': 'William Faulkner',
 'The grapes of wrath': 'John Steinbeck',
 'The sun also rises': 'Ernest Hemingway',
 'Absalom, absalom!': 'William Faulkner',
 'The house of mirth': 'Edith Wharton',
 'A time to kill': 'John Grisham',
 'Sarah,plain and tell': 'Patricia MacLachlan',
 'In the early hours': 'Khurram Murad',
 'Sweet sixteen': 'Bolaji Abdullahi'}

In [47]:
LibraryCat1 = {'To kill a mockingbird':'Harper Lee','Gone with the wind':'Margaret Mitchell','As I lay dying':'William Faulkner',
      'The grapes of wrath':'John Steinbeck','The sun also rises':'Ernest Hemingway','Absalom, absalom!':'William Faulkner',
      'The house of mirth':'Edith Wharton','A time to kill':'John Grisham','Sarah,plain and tell':'Patricia MacLachlan'}

def librarycati(Search, **Update):
    #Search = input('Enter book title: ')
    for booktitles,authors in LibraryCat1.items():
        if Search == booktitles:
            print(f'author is: {authors}')
            break
    else:
        print("booktitle is not in LC")

In [48]:
librarycati("Search", In the early hours = "Khurram Murad")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2602207516.py, line 1)

In [49]:
def myfunc(*a):
  return len(a)

In [61]:
tuple(map(myfunc,("apple","cherry")))

(5, 6)

In [52]:
x = map(myfunc,('apple', 'banana', 'cherry'))

In [62]:
fruits = ("orange","pawpaw","lemon")
tuple(map(lambda a: len(a), fruits))

(6, 6, 5)

In [63]:
fruits = ("orange","pawpaw","lemon")
tuple(filter(lambda a: len(a) > 5, fruits))

('orange', 'pawpaw')

In [64]:
#fruits = ("orange","pawpaw","lemon")
tuple(map(lambda a: len(a) > 5, fruits))

(True, True, False)

In [65]:
def root(x,y):
    return x**(1/y)

In [66]:
root = lambda x, y: x ** (1/y)

In [67]:
root(25,2)

5.0

In [68]:
root(8,3)

2.0

In [104]:
ab = [6,2,3,9,1,5]
srt = list(map(lambda x: x, ab))

In [105]:
srt.sort()
print(srt)

[1, 2, 3, 5, 6, 9]


In [106]:
list1 = [2, 6, 8, 10, 11, 4, 12, 7, 13, 17, 0, 3, 21]


In [109]:
greater9 = list(filter(lambda a:a > 9, list1))

In [110]:
greater9

[10, 11, 12, 13, 17, 21]

In [111]:
list2 = [2, 6, 8, 10, 11, 4, 12, 7, 13, 17, 0, 3, 21]
mod2 = list(map(lambda a: a % 2, list2))

In [112]:
mod2

[0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1]

In [2]:
def get_quotient(numerator, denominator):
    try:
        quotient = numerator/denominator
        return quotient
    except:
        return ("function not working")

In [3]:
get_quotient(20,0)

'function not working'

In [5]:
def get_quotient(numerator, denominator):
    try:
        quotient = numerator/denominator
        return quotient
    except Exception as e:
        return e

In [6]:
get_quotient(20,0)

ZeroDivisionError('division by zero')

In [7]:
import data_module as dm

In [9]:
dm.calculate_mean([12,13,14,11,13,15])

13.0

In [10]:
from data_module import calculate_mean

In [11]:
calculate_mean([12,13,14,11,13,15])

13.0

In [2]:
import math

In [5]:
x = math.sqrt(225)
print(f"The square root of x is {x}")

The square root of x is 15.0


In [6]:
list_all= dir(math)
print('Functions in the math module: {}'.format(list_all))

Functions in the math module: ['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [8]:
math.pow(5,2)

25.0

In [9]:
height  = [1.8, 1.5, 1.6, 2.0, 1.3]
weight = [56.9, 89.6, 90.8, 30.0, 67.7]
# bmi = weight /height**2

In [10]:
round(weight[0]/height[0]**2,2)

17.56

In [11]:
bmi = [round(w/h**2,2) for w,h in zip(weight,height)]

In [12]:
bmi

[17.56, 39.82, 35.47, 7.5, 40.06]

In [19]:
from numpy import array, round
np_height = array(height)

In [21]:
np_weight = array(weight)
np_bmi = round(np_weight/(np_height **2), 2)

In [22]:
np_bmi

array([17.56, 39.82, 35.47,  7.5 , 40.06])

In [23]:
np_bmi[1:4]

array([39.82, 35.47,  7.5 ])

In [24]:
np_bmi.mean()

28.082

In [25]:
np_bmi.std()

13.192171011626556

In [26]:
np_bmi.shape

(5,)

In [27]:
type(np_bmi)

numpy.ndarray

In [28]:
# [120, 135, 150, 145, 155, 160, 170, 180, 190, 200, 210, 220]
multi_array = array([[120, 135, 150],
                       [145, 155, 160],
                       [170, 180, 190],
                       [200, 210, 220]])

In [29]:
multi_array

array([[120, 135, 150],
       [145, 155, 160],
       [170, 180, 190],
       [200, 210, 220]])

In [30]:
# Data Exploration:

'''Problem: You have a dataset containing information about customer orders. 
Use Python to calculate the total number of orders, the average order value, and the most common product purchased.'''

supermarket_data = [
    {'TransactionID': 1, 'Product': 'Milk', 'Price': 2.99},
    {'TransactionID': 2, 'Product': 'Bread', 'Price': 1.99},
    {'TransactionID': 3, 'Product': None, 'Price': 3.49},
    {'TransactionID': 4, 'Product': 'Eggs', 'Price': 1.79},
    {'TransactionID': 5, 'Product': 'Milk', 'Price': 4.99},
    {'TransactionID': 6, 'Product': 'Bread', 'Price': 4.99},
    {'TransactionID': 7, 'Product': 'Milk', 'Price': 4.99}
]

In [50]:
count = 0
for order in supermarket_data:
    count += 1
print(count)

7


In [51]:
total_price = 0
for price in supermarket_data:
    total_price += price["Price"]
print(total_price)

25.230000000000004


In [53]:
average = total_price/count
print(average)

3.604285714285715


In [67]:
product_counts = {}
for product in supermarket_data:
    product = product["Product"]
    if product in product_counts:
        product_counts[product] += 1
    else:
        product_counts[product] = 1
print(f' {product} is the most purchased')

 Milk is the most purchased


In [68]:
product_counts

{'Milk': 3, 'Bread': 2, None: 1, 'Eggs': 1}

In [1]:
#Data Cleaning:

'''Problem: Your dataset has missing values in a column. 
Write a Python script to identify and count the missing values in that column.'''

supermarket_data = [
    {'TransactionID': 1, 'Product': 'Milk', 'Price': 2.99},
    {'TransactionID': 2, 'Product': 'Bread', 'Price': 1.99},
    {'TransactionID': 3, 'Product': None, 'Price': 3.49},
    {'TransactionID': 4, 'Product': 'Eggs', 'Price': 1.79},
    {'TransactionID': 5, 'Product': 'Milk', 'Price': 4.99},
    {'TransactionID': 6, 'Product': None, 'Price': 4.99},
    {'TransactionID': 7, 'Product': 'Milk', 'Price': 4.99}
]

In [10]:
missing_values = 0
for product in supermarket_data:
    product = product["Product"]
    if product == None:
        missing_values += 1
print (missing_values)

2


In [11]:
#Data Preprocessing:

'''Problem: You have a dataset with a 'date' column in the format 'yyyy-mm-dd'. 
Write a Python function to extract the year and month from the date and store them in separate lists.'''

dataset = [
    {'ID': 1, 'Date': '2023-04-15', 'Value': 42},
    {'ID': 2, 'Date': '2023-05-20', 'Value': 56},
    {'ID': 3, 'Date': '2023-04-02', 'Value': 34},
    {'ID': 4, 'Date': '2023-06-10', 'Value': 78},
    {'ID': 5, 'Date': '2023-05-12', 'Value': 65},
]

In [15]:
def extract_year_and_month (data, date_column):
    years = []
    months =[]
    
    for entry in data:
        date = entry.get(date_column)
        if date:
            year,month,*_ = date.split('-')
            years.append(year)
            months.append(month)
    return years, months

In [16]:
years, months = extract_year_and_month(dataset, 'Date')

In [17]:
print(f'years = {years}')
print(f'months = {months}')

years = ['2023', '2023', '2023', '2023', '2023']
months = ['04', '05', '04', '06', '05']


In [1]:
#Data Filtering and Transformation:
'''Problem: You have a list of student records as dictionaries. 
Filter the records of students who scored above a certain threshold and calculate their final grades.'''

student_records = [
    {'ID': 1, 'Name': 'Alice', 'Math_Score': 85, 'English_Score': 78},
    {'ID': 2, 'Name': 'Bob', 'Math_Score': 92, 'English_Score': 88},
    {'ID': 3, 'Name': 'Charlie', 'Math_Score': 78, 'English_Score': 95},
    {'ID': 4, 'Name': 'David', 'Math_Score': 65, 'English_Score': 72},
    {'ID': 5, 'Name': 'Eve', 'Math_Score': 89, 'English_Score': 91},
]
threshold = 80

In [2]:
for item in student_records:
    score1 = item["Math_Score"]
    score2 = item["English_Score"]
    name = item['Name']
    if score1 >= 80 and score2 >= 80:
        print (f' {name} has a score greater than 80')

 Bob has a score greater than 80
 Eve has a score greater than 80


In [3]:
for student in student_records:
    item1 = student['Math_Score']
    item2 = student['English_Score']
    name = student['Name']
    final_grades = item1 + item2
    print (f' {name} has a total score of: {final_grades}')

 Alice has a total score of: 163
 Bob has a total score of: 180
 Charlie has a total score of: 173
 David has a total score of: 137
 Eve has a total score of: 180


In [8]:
for student in student_records:
    final_grades = sum(student[values] for values in ['Math_Score','English_Score'])
    print (f' {name} has a total score of: {final_grades}')

 Eve has a total score of: 163
 Eve has a total score of: 180
 Eve has a total score of: 173
 Eve has a total score of: 137
 Eve has a total score of: 180


In [9]:
#Numpy
import numpy as np

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [13]:
np.random.random((2,4))

array([[0.90397814, 0.60731146, 0.20340369, 0.78034293],
       [0.44829573, 0.63314984, 0.3719928 , 0.16422693]])

In [14]:
ratings = np.array([[94,89,63], [93,92,48], [92,94,56]])

ratings

array([[94, 89, 63],
       [93, 92, 48],
       [92, 94, 56]])

In [15]:
ratings[0,0]

94

In [21]:
ratings[0:2]

array([[94, 89, 63],
       [93, 92, 48]])

In [22]:
ratings[0,:2]

array([94, 89])

In [23]:
ratings[0:2,0:2]

array([[94, 89],
       [93, 92]])

In [24]:
ratings[ratings > 90]

array([94, 93, 92, 92, 94])

In [37]:
#adding extra row to an array using 'append' or we say appending to the columns
ratings1 = np.append(ratings, [[82,92,96]], axis = 0)
print(ratings1)

[[94 89 63]
 [93 92 48]
 [92 94 56]
 [82 92 96]]


In [66]:
#adding extra column to an array or we say appending to the rows
ratings2 = np.append(ratings1, np.array([[91,92,86,90]])\
                               .reshape(4, 1), axis=1)

print(ratings2)

[[94 89 63 91]
 [93 92 48 92]
 [92 94 56 86]
 [82 92 96 90]]


In [65]:
#deleting row from an array 
ratings_row_delete = np.delete(ratings1, [1], axis = 0)
ratings_row_delete

array([[94, 89, 63],
       [92, 94, 56],
       [82, 92, 96]])

In [55]:
#deleting column from an array 
ratings_column_delete = np.delete(ratings2, [1], axis = 1)
ratings_column_delete

array([[94, 63, 91],
       [93, 48, 92],
       [92, 56, 86],
       [82, 96, 90]])

In [57]:
#sum of all elements in an array
ratings.sum()

721

In [61]:
#sum of each row
rowTotal = ratings.sum(axis = 1)
rowTotal

array([246, 233, 242])

In [62]:
#sum of each column
columnTotal = ratings.sum(axis = 0)
columnTotal

array([279, 275, 167])

In [67]:
# Min of each row.
ratings.min(axis=1)

array([63, 48, 56])

In [68]:
# Max of each column.
ratings.max(axis=0)

array([94, 94, 63])

In [55]:
'''Find the 3 most profitable companies in the entire world.
Output the result along with the corresponding company name.
Sort the result based on profits in descending order.'''

#DataFrame: forbes_global_2010_2014

result = forbes_global_2010_2014.groupby('company')['profits'].sum().reset_index().sort_values(by='profits', ascending=False)
result['rank'] = result['profits'].rank(method='min', ascending=False)
result = result[result['rank'] <= 3][['company', 'profits']]

NameError: name 'forbes_global_2010_2014' is not defined

In [5]:
import numpy as np
import pandas as pd
forbes = pd.read_csv("C:/Users/USER/Desktop/AltSchool Africa/Forbes_2000_top_company.csv")

In [7]:
forbes.head()

2022 Ranking                         Organization Name  \
0             1                        Berkshire Hathaway   
1             2                                      ICBC   
2             3  Saudi Arabian Oil Company (Saudi Aramco)   
3             4                            JPMorgan Chase   
4             5                   China Construction Bank   

                 Industry        Country  Year Founded  \
0  Diversified Financials  United States          1939   
1                 Banking          China          1984   
2    Oil & Gas Operations   Saudi Arabia          1933   
3  Diversified Financials  United States          2000   
4                 Banking          China          2014   

                        CEO  Revenue (Billions)  Profits (Billions)  \
0     Warren Edward Buffett              276.09               89.80   
1                    Shu Gu              208.13               54.03   
2  Amin bin Hasan Al-Nasser              400.38              105.36   
3               Jamie Dimon              124.54               42.12   
4                 Wang Zuji              202.07               46.89   

   Assets (Billions)  Market Value (Billions) Total Employees  
0             958.78                   741.48        372000.0  
1            5518.51                   214.42          449296  
2             576.04                  2292.08         68493.0  
3            3954.69                   374.45        271025.0  
4            4746.95                   181.32          352621

In [13]:
forbes.columns[:]

Index(['2022 Ranking', 'Organization Name', 'Industry', 'Country',
       'Year Founded', 'CEO', 'Revenue (Billions)', 'Profits (Billions)',
       'Assets (Billions)', 'Market Value (Billions)', 'Total Employees'],
      dtype='object')

In [56]:
profitable = forbes.groupby('Organization Name')['Profits (Billions)'].max().reset_index().sort_values(by='Profits (Billions)',
                                                                                         ascending=False)
profitable

In [54]:
profitable1 = profitable.iloc[:3]
profitable1

Organization Name  Profits (Billions)
1547  Saudi Arabian Oil Company (Saudi Aramco)              105.36
133                                      Apple              100.56
284                         Berkshire Hathaway               89.80

In [1]:
# Create new inventory for a supermarket
Store = open('store.csv', 'a')
import pandas as pd

In [2]:
def add_item():
    product_name = input("Enter the name of product: ")
    quantity = int(input("Enter the quantity of product: "))
    price = float(input("Enter the price of product: "))
    
    Store = pd.DataFrame({'Product Name':[product_name], 'Quantity':[quantity], 'Price':[price]})
    #Store = Store[['product_name', 'quantity', 'price']]
    Store = Store.write('store.csv', 'a')
    return Store
    print(f'Product {product_name} added succesfully!\n')
    

In [ ]:
add_item()

In [1]:
from inventory_file import run_inventory_ms

In [2]:
import pandas as pd

In [3]:
run_inventory_ms()


Inventory Management System
1. Add Product
2. View Inventory
3. Search Product
4. Delete product
5. Exit
Enter any of option(1-5): 5
You have successfully exited the IMS
